services:
  - type: web
    name: universal-classifier
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

    disk:
      name: model-storage
      mountPath: /opt/render/project/src/cache   # <-- UPDATED
      sizeGB: 5
